backend:
  name: git-gateway
  branch: master
media_folder: publicimg/img #images that are uploaded via Netlify Cms interface will be stored in this folder
public_folder: img #I dont know
collections:
  - name: "Semester" # Used in routes, e.g., /admin/collections/blog
    label: "CourseLECTURE" # Used in the UI
    folder: "courses" # The path to the folder where the markdown files are stored
    create: true # Allow users to create new markdown files.
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for front matter. You will need to modify fields according to your project.
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Download", name: "download", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Sem", name: "Semester", widget: "string", default: "Admin"}
      - {label: "Body", name: "body", widget: "markdown"}
